[workspace]
members = [
    "workspace",
    "rustysynth",
    "rustysynth-soundfont",
    "rustysynth-midi",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"