[package]
name = "workspace"
version = "0.1.0"
edition.workspace = true

[dependencies]
rustysynth = { path = "../rustysynth" }
rustysynth-soundfont = { path = "../rustysynth-soundfont" }
rustysynth-midi = { path = "../rustysynth-midi" }
